displayName=Item Tracker
author=Oveduumnakal
description=Track quantity and value of gathered or processed items
tags=item,track,value,price,quantity,gather,profit,skilling,wiki
plugins=com.oveduumnakal.ItemTrackerPlugin
version=
build=standard
