/*
 * Copyright (c) 2026, Oveduumnakal
 * All rights reserved.
 */
package com.oveduumnakal;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

import lombok.extern.slf4j.Slf4j;

/**
 * Assigns an item to a category using the bundled {@code item-categories.txt}
 * snapshot of OSRS Wiki category membership (regenerated by
 * {@code scripts/gen-item-categories.py}), keyed by lower-cased item name.
 * Charge and dose variants such as {@code Ring of dueling(4)} resolve by
 * stripping the trailing parenthetical back to the base page name; anything
 * the snapshot doesn't know falls into {@link #OTHER}.
 *
 * <p>Lookups stay offline, instant, and deterministic — the wiki is only
 * consulted when a maintainer regenerates the snapshot.
 */
@Slf4j
public final class ItemCategoryClassifier
{
	/** Catch-all bucket for items the snapshot doesn't cover. */
	public static final String OTHER = "Other";

	/** Lower-cased item name → category, loaded once from the bundled snapshot. */
	private static final Map<String, String> CATEGORIES = loadCategories();

	private ItemCategoryClassifier()
	{
	}

	/**
	 * @param itemName the item's display name
	 * @return the category name for {@code itemName}, or {@link #OTHER} when the snapshot has no entry
	 */
	public static String classify(String itemName)
	{
		if (itemName == null || itemName.trim().isEmpty())
			return OTHER;

		String name = itemName.trim().toLowerCase(Locale.ROOT);
		String category = CATEGORIES.get(name);
		if (category != null)
			return category;

		String base = name.replaceFirst("\\s*\\([^)]*\\)$", "");
		return CATEGORIES.getOrDefault(base, OTHER);
	}

	/** Loads the bundled {@code name<TAB>category} snapshot; a load failure degrades to an empty map. */
	private static Map<String, String> loadCategories()
	{
		Map<String, String> categories = new HashMap<>();
		try (BufferedReader reader = new BufferedReader(new InputStreamReader(
				ItemCategoryClassifier.class.getResourceAsStream("item-categories.txt"), StandardCharsets.UTF_8)))
		{
			String line;
			while ((line = reader.readLine()) != null)
			{
				int tab = line.indexOf('\t');
				if (tab > 0)
					categories.put(line.substring(0, tab), line.substring(tab + 1));
			}
		}
		catch (Exception ex)
		{
			log.warn("Failed to load the item category snapshot; auto-categorize will assign \"{}\" only", OTHER, ex);
		}

		return categories;
	}
}
